name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - package.json

permissions: {}

jobs:
  check:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      version_changed: ${{ steps.version.outputs.changed }}
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - name: Check version changes
        uses: EndBug/version-check@5102328418c0130d66ca712d755c303e93368ce2 # v2.1.7
        id: version
        with:
          static-checking: localIsNew
          file-url: https://unpkg.com/coc-oxc@latest/package.json
          file-name: package.json

      - name: Set version name
        if: steps.version.outputs.changed == 'true'
        run: |
          echo "Version change found! New version: ${{ steps.version.outputs.version }} (${{ steps.version.outputs.version_type }})"

  release:
    needs: check
    if: needs.check.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - uses: oxc-project/setup-node@fdbf0dfd334c4e6d56ceeb77d91c76339c2a0885 # v1.0.4

      - run: pnpm run build

      - run: npm install -g npm@latest # For trusted publishing support

      - run: pnpm publish --tag latest --provenance --access public

      - name: Create GitHub Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
        with:
          draft: false
          name: v${{ needs.check.outputs.version }}
          tag_name: v${{ needs.check.outputs.version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
